begin;

insert into public.products (
  id,
  name,
  slug,
  short_description,
  description,
  category,
  price,
  old_price,
  materials,
  wood_type,
  metal,
  dimensions,
  weight,
  fastening,
  sku,
  stock,
  production_time,
  is_available,
  is_made_to_order,
  is_featured,
  is_new,
  is_bestseller,
  wildberries_url,
  created_at,
  updated_at
)
values
  (
    '10000000-0000-4000-8000-000000000001'::uuid,
    'Серьги «Тихая бухта»',
    'tikhaya-bukhta',
    'Лёгкие серьги из тёплой ольхи с серебряным контуром.',
    'Плавная форма напоминает линию закрытой морской бухты. Тонкая серебряная рамка подчёркивает естественный рисунок ольхи, а ручная шлифовка оставляет поверхность матовой и приятной на ощупь.',
    'earrings',
    3900,
    null,
    array['Натуральное дерево', 'Серебро 925 пробы']::text[],
    'Ольха',
    'Серебро 925 пробы',
    '32 × 14 × 4 мм',
    5,
    'Английский замок',
    'JT-ER-001',
    7,
    '3–5 рабочих дней',
    true,
    false,
    true,
    false,
    false,
    null,
    '2026-02-14T03:00:00.000Z'::timestamptz,
    '2026-07-08T03:00:00.000Z'::timestamptz
  ),
  (
    '10000000-0000-4000-8000-000000000002'::uuid,
    'Серьги «Северный ветер»',
    'severny-veter',
    'Удлинённые серьги из ореха и серебра с подвижной деталью.',
    'Строгий вытянутый силуэт оживает при движении благодаря серебряному шарниру. Тёмный орех делает пару графичной, но сохраняет мягкость природного материала.',
    'earrings',
    4600,
    null,
    array['Натуральное дерево', 'Серебро 925 пробы']::text[],
    'Орех',
    'Серебро 925 пробы',
    '48 × 11 × 4 мм',
    7,
    'Серебряная швенза с фиксатором',
    'JT-ER-002',
    4,
    '4–6 рабочих дней',
    true,
    false,
    false,
    false,
    false,
    null,
    '2026-01-29T03:00:00.000Z'::timestamptz,
    '2026-06-21T03:00:00.000Z'::timestamptz
  ),
  (
    '10000000-0000-4000-8000-000000000003'::uuid,
    'Серьги «Свет над Амуром»',
    'svet-nad-amurom',
    'Светлый клён и матовое серебро в мягкой округлой форме.',
    'Полукруги из клёна собраны так, чтобы рисунок древесины продолжался от одной детали к другой. Сатинированное серебро отражает свет спокойно, без избыточного блеска.',
    'earrings',
    4300,
    null,
    array['Натуральное дерево', 'Серебро 925 пробы']::text[],
    'Клён',
    'Серебро 925 пробы',
    '28 × 18 × 4 мм',
    6,
    'Пусета с серебряным фиксатором',
    'JT-ER-003',
    9,
    '3–5 рабочих дней',
    true,
    false,
    true,
    true,
    false,
    null,
    '2026-07-12T03:00:00.000Z'::timestamptz,
    '2026-07-12T03:00:00.000Z'::timestamptz
  ),
  (
    '10000000-0000-4000-8000-000000000004'::uuid,
    'Серьги «Кедровая линия»',
    'kedrovaya-liniya',
    'Тонкие серьги из кедра с лаконичной серебряной швензой.',
    'Узкая деревянная пластина подчёркивает продольное направление кедровых волокон. Небольшой вес делает эту модель удобной на весь день, а тёплый оттенок легко сочетается с базовыми цветами.',
    'earrings',
    3500,
    null,
    array['Натуральное дерево', 'Серебро 925 пробы']::text[],
    'Кедр',
    'Серебро 925 пробы',
    '42 × 8 × 3 мм',
    4,
    'Серебряная швенза с фиксатором',
    'JT-ER-004',
    12,
    '3–5 рабочих дней',
    true,
    false,
    true,
    false,
    true,
    null,
    '2025-11-18T03:00:00.000Z'::timestamptz,
    '2026-07-02T03:00:00.000Z'::timestamptz
  ),
  (
    '10000000-0000-4000-8000-000000000005'::uuid,
    'Подвеска «Исток»',
    'istok',
    'Подвеска из ореха с тонкой серебряной линией и цепочкой.',
    'В центре тёмной деревянной формы проходит серебряная линия, похожая на начало водного потока. Подвеска отполирована вручную и дополнена регулируемой серебряной цепочкой.',
    'pendants',
    5900,
    null,
    array['Натуральное дерево', 'Серебро 925 пробы']::text[],
    'Орех',
    'Серебро 925 пробы',
    '38 × 22 × 6 мм, цепочка 45–50 см',
    12,
    'Карабин',
    'JT-PD-001',
    6,
    '5–7 рабочих дней',
    true,
    false,
    true,
    false,
    true,
    null,
    '2025-12-03T03:00:00.000Z'::timestamptz,
    '2026-07-10T03:00:00.000Z'::timestamptz
  ),
  (
    '10000000-0000-4000-8000-000000000006'::uuid,
    'Подвеска «Туман над морем»',
    'tuman-nad-morem',
    'Светлая подвеска из клёна с серебряной вставкой мягкой формы.',
    'Матовый клён и прохладное серебро сходятся в асимметричном силуэте с размытыми границами. Лёгкая подвеска лежит близко к телу и подходит для многослойных сочетаний.',
    'pendants',
    4800,
    null,
    array['Натуральное дерево', 'Серебро 925 пробы', 'Текстильный шнур']::text[],
    'Клён',
    'Серебро 925 пробы',
    '34 × 25 × 5 мм, шнур 50 см',
    10,
    'Регулируемый серебряный замок',
    'JT-PD-002',
    8,
    '4–6 рабочих дней',
    true,
    false,
    true,
    true,
    false,
    null,
    '2026-07-05T03:00:00.000Z'::timestamptz,
    '2026-07-11T03:00:00.000Z'::timestamptz
  ),
  (
    '10000000-0000-4000-8000-000000000007'::uuid,
    'Подвеска «Течение»',
    'techenie',
    'Дубовая подвеска с объёмным серебряным элементом.',
    'Рельефная серебряная деталь проходит по поверхности дуба свободной непрерывной линией. Выразительная текстура материала делает каждую подвеску немного иной, сохраняя общий спокойный силуэт.',
    'pendants',
    6200,
    null,
    array['Натуральное дерево', 'Серебро 925 пробы']::text[],
    'Дуб',
    'Серебро 925 пробы',
    '46 × 20 × 7 мм, цепочка 55 см',
    16,
    'Карабин',
    'JT-PD-003',
    3,
    '6–8 рабочих дней',
    true,
    false,
    false,
    false,
    false,
    null,
    '2026-03-19T03:00:00.000Z'::timestamptz,
    '2026-06-30T03:00:00.000Z'::timestamptz
  ),
  (
    '10000000-0000-4000-8000-000000000008'::uuid,
    'Браслет «Каменный берег»',
    'kamenny-bereg',
    'Браслет из тёмного ореха с гладкой серебряной вставкой.',
    'Небольшие округлые звенья из ореха чередуются с прохладной серебряной деталью, напоминающей обточенный водой камень. Посадка регулируется удлинительной цепочкой.',
    'bracelets',
    5700,
    null,
    array['Натуральное дерево', 'Серебро 925 пробы', 'Ювелирный трос']::text[],
    'Орех',
    'Серебро 925 пробы',
    'Обхват 16–19 см, ширина 10 мм',
    18,
    'Карабин с удлинительной цепочкой',
    'JT-BR-001',
    5,
    '5–7 рабочих дней',
    true,
    false,
    true,
    false,
    false,
    null,
    '2026-01-11T03:00:00.000Z'::timestamptz,
    '2026-06-26T03:00:00.000Z'::timestamptz
  ),
  (
    '10000000-0000-4000-8000-000000000009'::uuid,
    'Браслет «Таёжная тропа»',
    'taezhnaya-tropa',
    'Гибкий браслет из кедровых элементов с серебряным акцентом.',
    'Кедровые детали различной длины складываются в спокойный ритм, похожий на неровную лесную тропу. Центральная бусина из серебра добавляет прохладный акцент и удерживает композицию.',
    'bracelets',
    4200,
    null,
    array['Натуральное дерево', 'Серебро 925 пробы', 'Эластичная ювелирная нить']::text[],
    'Кедр',
    'Серебро 925 пробы',
    'Обхват 16–18 см, ширина 8 мм',
    14,
    'Без застёжки, эластичная основа',
    'JT-BR-002',
    11,
    '4–6 рабочих дней',
    true,
    false,
    false,
    false,
    true,
    null,
    '2025-10-24T03:00:00.000Z'::timestamptz,
    '2026-07-06T03:00:00.000Z'::timestamptz
  ),
  (
    '10000000-0000-4000-8000-000000000010'::uuid,
    'Браслет «Полдень»',
    'polden',
    'Светлый браслет из клёна с тонким серебряным замком.',
    'Мягко скруглённые кленовые сегменты сохраняют светлый естественный оттенок древесины. Миниатюрный серебряный замок почти не нарушает цельную линию браслета.',
    'bracelets',
    3900,
    null,
    array['Натуральное дерево', 'Серебро 925 пробы', 'Ювелирный трос']::text[],
    'Клён',
    'Серебро 925 пробы',
    'Обхват 17–19 см, ширина 7 мм',
    13,
    'Серебряный карабин',
    'JT-BR-003',
    7,
    '4–6 рабочих дней',
    true,
    false,
    false,
    true,
    false,
    null,
    '2026-06-28T03:00:00.000Z'::timestamptz,
    '2026-07-09T03:00:00.000Z'::timestamptz
  ),
  (
    '10000000-0000-4000-8000-000000000011'::uuid,
    'Брелок «Маяк»',
    'mayak',
    'Дубовый брелок строгой геометрии со стальным кольцом.',
    'Вертикальная форма и небольшая металлическая насечка напоминают световой пояс маяка. Плотный дуб хорошо переносит ежедневное использование, постепенно приобретая индивидуальную патину.',
    'keychains',
    2100,
    null,
    array['Натуральное дерево', 'Нержавеющая сталь']::text[],
    'Дуб',
    'Нержавеющая сталь',
    '62 × 18 × 8 мм',
    22,
    'Разъёмное стальное кольцо 30 мм',
    'JT-KC-001',
    14,
    '3–5 рабочих дней',
    true,
    false,
    false,
    false,
    false,
    null,
    '2026-02-01T03:00:00.000Z'::timestamptz,
    '2026-06-12T03:00:00.000Z'::timestamptz
  ),
  (
    '10000000-0000-4000-8000-000000000012'::uuid,
    'Брелок «След тайги»',
    'sled-taygi',
    'Компактный кедровый брелок с рельефной линией волокон.',
    'Поверхность брелока обработана так, чтобы тактильно ощущался продольный рисунок кедра. Простая форма не цепляется за карман, а стальное кольцо рассчитано на повседневную нагрузку.',
    'keychains',
    1800,
    null,
    array['Натуральное дерево', 'Нержавеющая сталь']::text[],
    'Кедр',
    'Нержавеющая сталь',
    '48 × 24 × 7 мм',
    16,
    'Разъёмное стальное кольцо 25 мм',
    'JT-KC-002',
    18,
    '2–4 рабочих дня',
    true,
    false,
    false,
    false,
    false,
    null,
    '2025-12-14T03:00:00.000Z'::timestamptz,
    '2026-06-18T03:00:00.000Z'::timestamptz
  ),
  (
    '10000000-0000-4000-8000-000000000013'::uuid,
    'Брелок «Речной камень»',
    'rechnoy-kamen',
    'Округлый брелок из ореха с серебристой вставкой.',
    'Асимметричная деревянная форма отшлифована до гладкости речной гальки. Небольшая вставка из матовой стали защищает отверстие крепления и поддерживает лаконичный характер предмета.',
    'keychains',
    2400,
    null,
    array['Натуральное дерево', 'Нержавеющая сталь']::text[],
    'Орех',
    'Нержавеющая сталь',
    '52 × 31 × 9 мм',
    24,
    'Стальное кольцо с короткой цепочкой',
    'JT-KC-003',
    6,
    '3–5 рабочих дней',
    true,
    false,
    false,
    false,
    false,
    null,
    '2026-04-07T03:00:00.000Z'::timestamptz,
    '2026-06-29T03:00:00.000Z'::timestamptz
  ),
  (
    '10000000-0000-4000-8000-000000000014'::uuid,
    'Настольный объект «Горизонт»',
    'gorizont',
    'Небольшой настольный объект из ясеня с серебряной линией.',
    'Светлая цельная форма из ясеня разделена тонкой горизонтальной вставкой из серебра. Объект можно использовать как держатель для колец или оставить самостоятельным акцентом на рабочем столе.',
    'gifts',
    6800,
    null,
    array['Натуральное дерево', 'Серебро 925 пробы']::text[],
    'Ясень',
    'Серебро 925 пробы',
    '90 × 42 × 28 мм',
    95,
    null,
    'JT-GF-001',
    0,
    '7–10 рабочих дней',
    true,
    true,
    false,
    false,
    false,
    null,
    '2026-03-02T03:00:00.000Z'::timestamptz,
    '2026-06-22T03:00:00.000Z'::timestamptz
  ),
  (
    '10000000-0000-4000-8000-000000000015'::uuid,
    'Подарочный набор «Тёплый берег»',
    'teply-bereg',
    'Подвеска и небольшой брелок из ореха в подарочной коробке.',
    'Два предмета из одной заготовки ореха объединены общим рисунком древесины: лаконичная подвеска с серебряной деталью и компактный брелок. Цена набора ниже стоимости изделий по отдельности; упаковка и карточка по уходу уже включены.',
    'gifts',
    7400,
    8200,
    array['Натуральное дерево', 'Серебро 925 пробы', 'Нержавеющая сталь']::text[],
    'Орех',
    'Серебро 925 пробы и нержавеющая сталь',
    'Подвеска 36 × 20 мм, брелок 48 × 22 мм',
    38,
    'Карабин и разъёмное кольцо',
    'JT-GF-002',
    0,
    '6–9 рабочих дней',
    true,
    true,
    true,
    false,
    false,
    null,
    '2026-05-20T03:00:00.000Z'::timestamptz,
    '2026-07-03T03:00:00.000Z'::timestamptz
  )
on conflict (slug) do update
set
  name = excluded.name,
  short_description = excluded.short_description,
  description = excluded.description,
  category = excluded.category,
  price = excluded.price,
  old_price = excluded.old_price,
  materials = excluded.materials,
  wood_type = excluded.wood_type,
  metal = excluded.metal,
  dimensions = excluded.dimensions,
  weight = excluded.weight,
  fastening = excluded.fastening,
  sku = excluded.sku,
  stock = excluded.stock,
  production_time = excluded.production_time,
  is_available = excluded.is_available,
  is_made_to_order = excluded.is_made_to_order,
  is_featured = excluded.is_featured,
  is_new = excluded.is_new,
  is_bestseller = excluded.is_bestseller,
  wildberries_url = excluded.wildberries_url,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

with image_assets (
  asset_key,
  image_url,
  alt_text,
  names_product
) as (
  values
    (
      'heroWoodSilver',
      '/images/hero-silver-jewelry-wood.webp',
      'Серебряное украшение рядом с натуральным деревом',
      false
    ),
    (
      'silverOnStone',
      '/images/product-ring-stone.webp',
      'Серебряная деталь на светлом камне, крупный план',
      true
    ),
    (
      'silverOnHand',
      '/images/product-ring-hand.webp',
      'Серебряное украшение на руке',
      true
    ),
    (
      'pendantShadow',
      '/images/product-necklace-shadow.webp',
      'Подвеска в мягком естественном свете',
      true
    ),
    (
      'pendantWorn',
      '/images/product-necklace-worn.webp',
      'Подвеска на человеке',
      true
    ),
    (
      'darkEarrings',
      '/images/product-earrings-dark.webp',
      'Тёмные серьги с выразительной природной фактурой',
      true
    ),
    (
      'wornEarrings',
      '/images/product-earrings-worn.webp',
      'Лаконичные серьги на человеке',
      true
    ),
    (
      'workshop',
      '/images/editorial-jewelry-workshop.webp',
      'Рабочее место в ювелирной мастерской',
      false
    ),
    (
      'workbench',
      '/images/editorial-jewelry-workbench.webp',
      'Инструменты и материалы на верстаке',
      false
    ),
    (
      'craftHands',
      '/images/editorial-craft-hands.webp',
      'Ручная обработка небольшой детали',
      false
    ),
    (
      'woodCarving',
      '/images/editorial-wood-carving.webp',
      'Точная ручная обработка древесины',
      false
    ),
    (
      'woodGrain',
      '/images/editorial-wood-grain.webp',
      'Естественный рисунок древесных волокон',
      false
    ),
    (
      'woodShavings',
      '/images/editorial-wood-shavings.webp',
      'Древесная стружка после ручной обработки',
      false
    ),
    (
      'giftPackaging',
      '/images/editorial-gift-packaging.webp',
      'Минималистичная подарочная упаковка для украшения',
      false
    )
),
product_image_sets (
  product_id,
  product_index,
  product_name,
  asset_keys
) as (
  values
    (
      '10000000-0000-4000-8000-000000000001'::uuid,
      1,
      'Серьги «Тихая бухта»',
      array['darkEarrings', 'wornEarrings', 'woodGrain', 'craftHands', 'giftPackaging']::text[]
    ),
    (
      '10000000-0000-4000-8000-000000000002'::uuid,
      2,
      'Серьги «Северный ветер»',
      array['wornEarrings', 'darkEarrings', 'silverOnStone', 'workbench', 'giftPackaging']::text[]
    ),
    (
      '10000000-0000-4000-8000-000000000003'::uuid,
      3,
      'Серьги «Свет над Амуром»',
      array['darkEarrings', 'wornEarrings', 'heroWoodSilver', 'woodGrain', 'giftPackaging']::text[]
    ),
    (
      '10000000-0000-4000-8000-000000000004'::uuid,
      4,
      'Серьги «Кедровая линия»',
      array['wornEarrings', 'darkEarrings', 'craftHands', 'woodCarving', 'giftPackaging']::text[]
    ),
    (
      '10000000-0000-4000-8000-000000000005'::uuid,
      5,
      'Подвеска «Исток»',
      array['pendantShadow', 'pendantWorn', 'woodGrain', 'workshop', 'giftPackaging']::text[]
    ),
    (
      '10000000-0000-4000-8000-000000000006'::uuid,
      6,
      'Подвеска «Туман над морем»',
      array['pendantWorn', 'pendantShadow', 'heroWoodSilver', 'craftHands', 'giftPackaging']::text[]
    ),
    (
      '10000000-0000-4000-8000-000000000007'::uuid,
      7,
      'Подвеска «Течение»',
      array['pendantShadow', 'pendantWorn', 'silverOnStone', 'woodCarving', 'giftPackaging']::text[]
    ),
    (
      '10000000-0000-4000-8000-000000000008'::uuid,
      8,
      'Браслет «Каменный берег»',
      array['silverOnHand', 'silverOnStone', 'woodGrain', 'craftHands', 'giftPackaging']::text[]
    ),
    (
      '10000000-0000-4000-8000-000000000009'::uuid,
      9,
      'Браслет «Таёжная тропа»',
      array['silverOnStone', 'silverOnHand', 'woodCarving', 'woodGrain', 'giftPackaging']::text[]
    ),
    (
      '10000000-0000-4000-8000-000000000010'::uuid,
      10,
      'Браслет «Полдень»',
      array['silverOnHand', 'silverOnStone', 'heroWoodSilver', 'workbench', 'giftPackaging']::text[]
    ),
    (
      '10000000-0000-4000-8000-000000000011'::uuid,
      11,
      'Брелок «Маяк»',
      array['woodCarving', 'woodGrain', 'woodShavings', 'craftHands', 'giftPackaging']::text[]
    ),
    (
      '10000000-0000-4000-8000-000000000012'::uuid,
      12,
      'Брелок «След тайги»',
      array['woodGrain', 'woodCarving', 'craftHands', 'workbench', 'giftPackaging']::text[]
    ),
    (
      '10000000-0000-4000-8000-000000000013'::uuid,
      13,
      'Брелок «Речной камень»',
      array['woodCarving', 'woodShavings', 'woodGrain', 'silverOnStone', 'giftPackaging']::text[]
    ),
    (
      '10000000-0000-4000-8000-000000000014'::uuid,
      14,
      'Настольный объект «Горизонт»',
      array['heroWoodSilver', 'woodGrain', 'woodCarving', 'workshop', 'giftPackaging']::text[]
    ),
    (
      '10000000-0000-4000-8000-000000000015'::uuid,
      15,
      'Подарочный набор «Тёплый берег»',
      array['giftPackaging', 'heroWoodSilver', 'pendantShadow', 'woodGrain', 'craftHands']::text[]
    )
)
insert into public.product_images (
  id,
  product_id,
  image_url,
  alt_text,
  sort_order
)
select
  (
    '20000000-0000-4000-8000-'
    || lpad(image_set.product_index::text, 8, '0')
    || lpad(selected.ordinality::text, 4, '0')
  )::uuid,
  image_set.product_id,
  asset.image_url,
  case
    when asset.names_product
      then image_set.product_name || '. ' || asset.alt_text
    else asset.alt_text
  end,
  (selected.ordinality - 1)::integer
from product_image_sets as image_set
cross join lateral unnest(image_set.asset_keys)
  with ordinality as selected (asset_key, ordinality)
join image_assets as asset using (asset_key)
on conflict (product_id, sort_order) do update
set
  image_url = excluded.image_url,
  alt_text = excluded.alt_text;

commit;
